name: Deploy Infrastructure Templates

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Deliver Application" ]
    types:
      - completed

jobs:
  deploy-render-templates:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v6
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Initialize Terraform environment
        working-directory: infrastructure/templates/render
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_STATE_SECRET_ACCESS_KEY }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET_NAME }}" \
            -backend-config="endpoints={\"s3\": \"https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com\"}"
      - name: Deploy Render templates
        working-directory: infrastructure/templates/render
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_STATE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_STATE_SECRET_ACCESS_KEY }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_OWNER_ID: ${{ secrets.RENDER_OWNER_ID }}
          TF_LOG: INFO
          TF_VAR_postgres_database_name: ${{ secrets.POSTGRES_DATABASE_NAME }}
          TF_VAR_postgres_instance_name: ${{ secrets.POSTGRES_INSTANCE_NAME }}
          TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
          TF_VAR_web_service_name: ${{ secrets.WEB_SERVICE_NAME }}
        run: terraform apply -auto-approve
      - name: Trigger deployment of Render services
        run: curl ${{ secrets.RENDER_DEPLOYMENT_HOOK_URL }}
